### ISSUE TITLE
Running `sudo` causes authd to log "WARN rpc error: code = NotFound desc ="

### ISSUE THREAD

**Issue by adombeck** [ubuntu/authd#468]
### Describe the issue

authd prints unhelpful warning messages to the journal when `sudo` is executed.

### Where does the issue happens

- [ ] I can reproduce the issue in the graphical display manager
- [ ] I can reproduce the issue on a terminal with "login"

### Steps to reproduce it

1. Ensure that `authd` and `authd-msentraid` are running
2. Follow the output of `authd`:
   ```
   sudo journalctl -u authd.service -f
   ```
3. Run any command via `sudo` in another terminal:
   ```
   sudo ls
   ```
4. Observe how `authd` logs `WARN rpc error: code = NotFound desc =`

**Comment by adombeck** [comment]
I looked into this today. The error is printed here: https://github.com/ubuntu/authd/blob/b125c84f6ad4c1c0bc441866aa404834b8969849/internal/services/errmessages/redactor.go#L18-L21

The method that's called when running `sudo` is `GetPasswdByName` and the `NotFound` error is returned here: https://github.com/ubuntu/authd/blob/b125c84f6ad4c1c0bc441866aa404834b8969849/internal/services/nss/nss.go#L40-L57

I see multiple ways to avoid spamming the log with these errors:
1. Don't print each error with `WARNING` level in `RedactErrorInterceptor`. Instead, we could log those errors which we want to log directly in the service method implementations.
2. Define a `SilentError` struct which we wrap errors that we don't want to log in.

@ubuntu/enterprise-desktop-team what do you think?

**Comment by adombeck** [comment]
@denisonbarbosa any thoughts on this?

**Comment by denisonbarbosa** [comment]
Does this also happen on the edge version? IIRC, we had some issues with the NSS module not printing the error logs correctly but we fixed it on #403.

**Comment by adombeck** [comment]
Yes, it also happens in the edge version

**Comment by denisonbarbosa** [comment]
This is actually easier to fix than expected :sweat_smile: ... Take a look [here](https://github.com/ubuntu/authd/blob/17530d217c2cdbae0c266ba848c5aa3eb0c63d0f/internal/services/nss/nss.go#L237). We are returning nothing as the gRPC error message, so replacing by `return status.Error(codes.NotFound, err.Error())` should be enough to fix the logs instead of adding more filters.

Then, the logs will show something like:
```
Aug 26 09:12:34 snapping-oidc authd[13305]: 2024/08/26 09:12:34 WARN rpc error: code = NotFound desc = no result matching pam_unix_non_existent: in UserByName
```

**Comment by adombeck** [comment]
Sure, we can add a description to the error, but I think the bigger issue here is that we spam the journal with that message whenever a user executes `sudo` on the system.

**Comment by denisonbarbosa** [comment]
Coming back to this... (sorry for the delay)

The PAM call for `pam_unix_non_existent` is a well-known query that multiple other processes also do. After some discussion with @didrocks, we thought it would be better to handle this well-known special case in our NSS module and return directly there instead of propagating this up the chain, as it is also not an error. Adding another layer of complexity by defining "silent" errors is not idiomatic Go and we should avoid this kind of behavior.

**Comment by adombeck** [comment]
>  it would be better to handle this well-known special case in our NSS module and return directly there 

Sounds good.

> defining "silent" errors is not idiomatic Go and we should avoid this kind of behavior.

I disagree, but we don't have to discuss that at this point since we have another solution.
